package com.tzy777.testssm.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table appointment
 *
 * @mbg.generated do_not_delete_during_merge 该注释于2018年06月27日11时20分15秒生成
 */
public class Appointment {
    /**
     * Database Column Remarks:
     *   图书ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.book_id
     *
     * @mbg.generated 该注释于2018年06月27日11时20分15秒生成
     */
    private Long bookId;

    /**
     * Database Column Remarks:
     *   学号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.student_id
     *
     * @mbg.generated 该注释于2018年06月27日11时20分15秒生成
     */
    private Long studentId;

    /**
     * Database Column Remarks:
     *   预约时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.appoint_time
     *
     * @mbg.generated 该注释于2018年06月27日11时20分15秒生成
     */
    private Date appointTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.book_id
     *
     * @return the value of appointment.book_id
     *
     * @mbg.generated 该注释于2018年06月27日11时20分15秒生成
     */
    public Long getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.book_id
     *
     * @param bookId the value for appointment.book_id
     *
     * @mbg.generated 该注释于2018年06月27日11时20分15秒生成
     */
    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.student_id
     *
     * @return the value of appointment.student_id
     *
     * @mbg.generated 该注释于2018年06月27日11时20分15秒生成
     */
    public Long getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.student_id
     *
     * @param studentId the value for appointment.student_id
     *
     * @mbg.generated 该注释于2018年06月27日11时20分15秒生成
     */
    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.appoint_time
     *
     * @return the value of appointment.appoint_time
     *
     * @mbg.generated 该注释于2018年06月27日11时20分15秒生成
     */
    public Date getAppointTime() {
        return appointTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.appoint_time
     *
     * @param appointTime the value for appointment.appoint_time
     *
     * @mbg.generated 该注释于2018年06月27日11时20分15秒生成
     */
    public void setAppointTime(Date appointTime) {
        this.appointTime = appointTime;
    }
}