package com.tzy777.testssm.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table book
 *
 * @mbg.generated do_not_delete_during_merge 该注释于2018年06月27日11时20分15秒生成
 */
public class Book {
    /**
     * Database Column Remarks:
     *   图书ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_id
     *
     * @mbg.generated 该注释于2018年06月27日11时20分15秒生成
     */
    private Long bookId;

    /**
     * Database Column Remarks:
     *   图书名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.name
     *
     * @mbg.generated 该注释于2018年06月27日11时20分15秒生成
     */
    private String name;

    /**
     * Database Column Remarks:
     *   馆藏数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.number
     *
     * @mbg.generated 该注释于2018年06月27日11时20分15秒生成
     */
    private Integer number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_id
     *
     * @return the value of book.book_id
     *
     * @mbg.generated 该注释于2018年06月27日11时20分15秒生成
     */
    public Long getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_id
     *
     * @param bookId the value for book.book_id
     *
     * @mbg.generated 该注释于2018年06月27日11时20分15秒生成
     */
    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.name
     *
     * @return the value of book.name
     *
     * @mbg.generated 该注释于2018年06月27日11时20分15秒生成
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.name
     *
     * @param name the value for book.name
     *
     * @mbg.generated 该注释于2018年06月27日11时20分15秒生成
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.number
     *
     * @return the value of book.number
     *
     * @mbg.generated 该注释于2018年06月27日11时20分15秒生成
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.number
     *
     * @param number the value for book.number
     *
     * @mbg.generated 该注释于2018年06月27日11时20分15秒生成
     */
    public void setNumber(Integer number) {
        this.number = number;
    }
}