package com.tzy777.testssm.dao;

import com.tzy777.testssm.entity.Appointment;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppointmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbg.generated 该注释于2018年06月26日15时45分59秒生成
     */
    int deleteByPrimaryKey(@Param("bookId") Long bookId, @Param("studentId") Long studentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbg.generated 该注释于2018年06月26日15时45分59秒生成
     */
    int insert(Appointment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbg.generated 该注释于2018年06月26日15时45分59秒生成
     */
    Appointment selectByPrimaryKey(@Param("bookId") Long bookId, @Param("studentId") Long studentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbg.generated 该注释于2018年06月26日15时45分59秒生成
     */
    List<Appointment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbg.generated 该注释于2018年06月26日15时45分59秒生成
     */
    int updateByPrimaryKey(Appointment record);
}