package com.tzy777.testssm.dao;

import com.tzy777.testssm.entity.Book;
import java.util.List;

public interface BookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated 该注释于2018年06月27日11时20分15秒生成
     */
    int deleteByPrimaryKey(Long bookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated 该注释于2018年06月27日11时20分15秒生成
     */
    int insert(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated 该注释于2018年06月27日11时20分15秒生成
     */
    Book selectByPrimaryKey(Long bookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated 该注释于2018年06月27日11时20分15秒生成
     */
    List<Book> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated 该注释于2018年06月27日11时20分15秒生成
     */
    int updateByPrimaryKey(Book record);
}